const data = [
  {
    id: 1,
    text: "Growing of cereals (except rice), leguminous crops and oil seeds",
    sic: "1110",
  },
  { id: 2, text: "Growing of rice", sic: "1120" },
  {
    id: 3,
    text: "Growing of vegetables and melons, roots and tubers",
    sic: "1130",
  },
  { id: 4, text: "Growing of sugar cane", sic: "1140" },
  { id: 5, text: "Growing of tobacco", sic: "1150" },
  { id: 6, text: "Growing of fibre crops", sic: "1160" },
  { id: 7, text: "Growing of other non-perennial crops", sic: "1190" },
  { id: 8, text: "Growing of grapes", sic: "1210" },
  { id: 9, text: "Growing of tropical and subtropical fruits", sic: "1220" },
  { id: 10, text: "Growing of citrus fruits", sic: "1230" },
  { id: 11, text: "Growing of pome fruits and stone fruits", sic: "1240" },
  {
    id: 12,
    text: "Growing of other tree and bush fruits and nuts",
    sic: "1250",
  },
  { id: 13, text: "Growing of oleaginous fruits", sic: "1260" },
  { id: 14, text: "Growing of beverage crops", sic: "1270" },
  {
    id: 15,
    text: "Growing of spices, aromatic, drug and pharmaceutical crops",
    sic: "1280",
  },
  { id: 16, text: "Growing of other perennial crops", sic: "1290" },
  { id: 17, text: "Plant propagation", sic: "1300" },
  { id: 18, text: "Raising of dairy cattle", sic: "1410" },
  { id: 19, text: "Raising of other cattle and buffaloes", sic: "1420" },
  { id: 20, text: "Raising of horses and other equines", sic: "1430" },
  { id: 21, text: "Raising of camels and camelids", sic: "1440" },
  { id: 22, text: "Raising of sheep and goats", sic: "1450" },
  { id: 23, text: "Raising of swine/pigs", sic: "1460" },
  { id: 24, text: "Raising of poultry", sic: "1470" },
  { id: 25, text: "Raising of other animals", sic: "1490" },
  { id: 26, text: "Mixed farming", sic: "1500" },
  { id: 27, text: "Support activities for crop production", sic: "1610" },
  { id: 28, text: "Farm animal boarding and care", sic: "1621" },
  {
    id: 29,
    text: "Support activities for animal production (other than farm animal boarding and care) n.e.c.",
    sic: "1629",
  },
  { id: 30, text: "Post-harvest crop activities", sic: "1630" },
  { id: 31, text: "Seed processing for propagation", sic: "1640" },
  {
    id: 32,
    text: "Hunting, trapping and related service activities",
    sic: "1700",
  },
  { id: 33, text: "Silviculture and other forestry activities", sic: "2100" },
  { id: 34, text: "Logging", sic: "2200" },
  {
    id: 35,
    text: "Gathering of wild growing non-wood products",
    sic: "2300",
  },
  { id: 36, text: "Support services to forestry", sic: "2400" },
  { id: 37, text: "Marine fishing", sic: "3110" },
  { id: 38, text: "Freshwater fishing", sic: "3120" },
  { id: 39, text: "Marine aquaculture", sic: "3210" },
  { id: 40, text: "Freshwater aquaculture", sic: "3220" },
  { id: 41, text: "Deep coal mines", sic: "5101" },
  { id: 42, text: "Open cast coal working", sic: "5102" },
  { id: 43, text: "Mining of lignite", sic: "5200" },
  { id: 44, text: "Extraction of crude petroleum", sic: "6100" },
  { id: 45, text: "Extraction of natural gas", sic: "6200" },
  { id: 46, text: "Mining of iron ores", sic: "7100" },
  { id: 47, text: "Mining of uranium and thorium ores", sic: "7210" },
  { id: 48, text: "Mining of other non-ferrous metal ores", sic: "7290" },
  {
    id: 49,
    text: "Quarrying of ortextntal and building stone, limestone, gypsum, chalk and slate",
    sic: "8110",
  },
  {
    id: 50,
    text: "Operation of gravel and sand pits; mining of clays and kaolin",
    sic: "8120",
  },
  { id: 51, text: "Mining of chemical and fertilizer minerals", sic: "8910" },
  { id: 52, text: "Extraction of peat", sic: "8920" },
  { id: 53, text: "Extraction of salt", sic: "8930" },
  { id: 54, text: "Other mining and quarrying n.e.c.", sic: "8990" },
  {
    id: 55,
    text: "Support activities for petroleum and natural gas mining",
    sic: "9100",
  },
  {
    id: 56,
    text: "Support activities for other mining and quarrying",
    sic: "9900",
  },
  { id: 57, text: "Processing and preserving of meat", sic: "10110" },
  { id: 58, text: "Processing and preserving of poultry meat", sic: "10120" },
  {
    id: 59,
    text: "Production of meat and poultry meat products",
    sic: "10130",
  },
  {
    id: 60,
    text: "Processing and preserving of fish, crustaceans and molluscs",
    sic: "10200",
  },
  { id: 61, text: "Processing and preserving of potatoes", sic: "10310" },
  { id: 62, text: "Manufacture of fruit and vegetable juice", sic: "10320" },
  {
    id: 63,
    text: "Other processing and preserving of fruit and vegetables",
    sic: "10390",
  },
  { id: 64, text: "Manufacture of oils and fats", sic: "10410" },
  {
    id: 65,
    text: "Manufacture of margarine and similar edible fats",
    sic: "10420",
  },
  { id: 66, text: "Liquid milk and cream production", sic: "10511" },
  { id: 67, text: "Butter and cheese production", sic: "10512" },
  { id: 68, text: "Manufacture of other milk products", sic: "10519" },
  { id: 69, text: "Manufacture of ice cream", sic: "10520" },
  { id: 70, text: "Grain milling", sic: "10611" },
  {
    id: 71,
    text: "Manufacture of breakfast cereals and cereals-based food",
    sic: "10612",
  },
  {
    id: 72,
    text: "Manufacture of starches and starch products",
    sic: "10620",
  },
  {
    id: 73,
    text: "Manufacture of bread; manufacture of fresh pastry goods and cakes",
    sic: "10710",
  },
  {
    id: 74,
    text: "Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes",
    sic: "10720",
  },
  {
    id: 75,
    text: "Manufacture of macaroni, noodles, couscous and similar farinaceous products",
    sic: "10730",
  },
  { id: 76, text: "Manufacture of sugar", sic: "10810" },
  {
    id: 77,
    text: "Manufacture of cocoa and chocolate confectionery",
    sic: "10821",
  },
  { id: 78, text: "Manufacture of sugar confectionery", sic: "10822" },
  { id: 79, text: "Tea processing", sic: "10831" },
  {
    id: 80,
    text: "Production of coffee and coffee substitutes",
    sic: "10832",
  },
  { id: 81, text: "Manufacture of condiments and seasonings", sic: "10840" },
  { id: 82, text: "Manufacture of prepared meals and dishes", sic: "10850" },
  {
    id: 83,
    text: "Manufacture of homogenized food preparations and dietetic food",
    sic: "10860",
  },
  { id: 84, text: "Manufacture of other food products n.e.c.", sic: "10890" },
  {
    id: 85,
    text: "Manufacture of prepared feeds for farm animals",
    sic: "10910",
  },
  { id: 86, text: "Manufacture of prepared pet foods", sic: "10920" },
  {
    id: 87,
    text: "Distilling, rectifying and blending of spirits",
    sic: "11010",
  },
  { id: 88, text: "Manufacture of wine from grape", sic: "11020" },
  {
    id: 89,
    text: "Manufacture of cider and other fruit wines",
    sic: "11030",
  },
  {
    id: 90,
    text: "Manufacture of other non-distilled fermented beverages",
    sic: "11040",
  },
  { id: 91, text: "Manufacture of beer", sic: "11050" },
  { id: 92, text: "Manufacture of malt", sic: "11060" },
  {
    id: 93,
    text: "Manufacture of soft drinks; production of mineral waters and other bottled waters",
    sic: "11070",
  },
  { id: 94, text: "Manufacture of tobacco products", sic: "12000" },
  {
    id: 95,
    text: "Preparation and spinning of textile fibres",
    sic: "13100",
  },
  { id: 96, text: "Weaving of textiles", sic: "13200" },
  { id: 97, text: "Finishing of textiles", sic: "13300" },
  {
    id: 98,
    text: "Manufacture of knitted and crocheted fabrics",
    sic: "13910",
  },
  { id: 99, text: "Manufacture of soft furnishings", sic: "13921" },
  { id: 100, text: "manufacture of canvas goods, sacks, etc.", sic: "13922" },
  { id: 101, text: "manufacture of household textiles", sic: "13923" },
  {
    id: 102,
    text: "Manufacture of woven or tufted carpets and rugs",
    sic: "13931",
  },
  { id: 103, text: "Manufacture of other carpets and rugs", sic: "13939" },
  {
    id: 104,
    text: "Manufacture of cordage, rope, twine and netting",
    sic: "13940",
  },
  {
    id: 105,
    text: "Manufacture of non-wovens and articles made from non-wovens, except apparel",
    sic: "13950",
  },
  {
    id: 106,
    text: "Manufacture of other technical and industrial textiles",
    sic: "13960",
  },
  { id: 107, text: "Manufacture of other textiles n.e.c.", sic: "13990" },
  { id: 108, text: "Manufacture of leather clothes", sic: "14110" },
  { id: 109, text: "Manufacture of workwear", sic: "14120" },
  {
    id: 110,
    text: "Manufacture of other men\u0027s outerwear",
    sic: "14131",
  },
  {
    id: 111,
    text: "Manufacture of other women\u0027s outerwear",
    sic: "14132",
  },
  { id: 112, text: "Manufacture of men\u0027s underwear", sic: "14141" },
  { id: 113, text: "Manufacture of women\u0027s underwear", sic: "14142" },
  {
    id: 114,
    text: "Manufacture of other wearing apparel and accessories n.e.c.",
    sic: "14190",
  },
  { id: 115, text: "Manufacture of articles of fur", sic: "14200" },
  {
    id: 116,
    text: "Manufacture of knitted and crocheted hosiery",
    sic: "14310",
  },
  {
    id: 117,
    text: "Manufacture of other knitted and crocheted apparel",
    sic: "14390",
  },
  {
    id: 118,
    text: "Tanning and dressing of leather; dressing and dyeing of fur",
    sic: "15110",
  },
  {
    id: 119,
    text: "Manufacture of luggage, handbags and the like, saddlery and harness",
    sic: "15120",
  },
  { id: 120, text: "Manufacture of footwear", sic: "15200" },
  { id: 121, text: "Sawmilling and planing of wood", sic: "16100" },
  {
    id: 122,
    text: "Manufacture of veneer sheets and wood-based panels",
    sic: "16210",
  },
  { id: 123, text: "Manufacture of assembled parquet floors", sic: "16220" },
  {
    id: 124,
    text: "Manufacture of other builders, carpentry and joinery",
    sic: "16230",
  },
  { id: 125, text: "Manufacture of wooden containers", sic: "16240" },
  {
    id: 126,
    text: "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials",
    sic: "16290",
  },
  { id: 127, text: "Manufacture of pulp", sic: "17110" },
  { id: 128, text: "Manufacture of paper and paperboard", sic: "17120" },
  {
    id: 129,
    text: "Manufacture of corrugated paper and paperboard, sacks and bags",
    sic: "17211",
  },
  {
    id: 130,
    text: "Manufacture of other paper and paperboard containers",
    sic: "17219",
  },
  {
    id: 131,
    text: "Manufacture of household and sanitary goods and of toilet requisites",
    sic: "17220",
  },
  { id: 132, text: "Manufacture of paper stationery", sic: "17230" },
  { id: 133, text: "Manufacture of wallpaper", sic: "17240" },
  {
    id: 134,
    text: "Manufacture of other articles of paper and paperboard n.e.c.",
    sic: "17290",
  },
  { id: 135, text: "Printing of newspapers", sic: "18110" },
  { id: 136, text: "Manufacture of printed labels", sic: "18121" },
  { id: 137, text: "Printing n.e.c.", sic: "18129" },
  { id: 138, text: "Pre-press and pre-media services", sic: "18130" },
  { id: 139, text: "Binding and related services", sic: "18140" },
  { id: 140, text: "Reproduction of sound recording", sic: "18201" },
  { id: 141, text: "Reproduction of video recording", sic: "18202" },
  { id: 142, text: "Reproduction of computer media", sic: "18203" },
  { id: 143, text: "Manufacture of coke oven products", sic: "19100" },
  { id: 144, text: "Mineral oil refining", sic: "19201" },
  {
    id: 145,
    text: "Other treatment of petroleum products (excluding petrochemicals manufacture)",
    sic: "19209",
  },
  { id: 146, text: "Manufacture of industrial gases", sic: "20110" },
  { id: 147, text: "Manufacture of dyes and pigments", sic: "20120" },
  {
    id: 148,
    text: "Manufacture of other inorganic basic chemicals",
    sic: "20130",
  },
  {
    id: 149,
    text: "Manufacture of other organic basic chemicals",
    sic: "20140",
  },
  {
    id: 150,
    text: "Manufacture of fertilizers and nitrogen compounds",
    sic: "20150",
  },
  { id: 151, text: "Manufacture of plastics in primary forms", sic: "20160" },
  {
    id: 152,
    text: "Manufacture of synthetic rubber in primary forms",
    sic: "20170",
  },
  {
    id: 153,
    text: "Manufacture of pesticides and other agrochemical products",
    sic: "20200",
  },
  {
    id: 154,
    text: "Manufacture of paints, varnishes and similar coatings, mastics and sealants",
    sic: "20301",
  },
  { id: 155, text: "Manufacture of printing ink", sic: "20302" },
  { id: 156, text: "Manufacture of soap and detergents", sic: "20411" },
  {
    id: 157,
    text: "Manufacture of cleaning and polishing preparations",
    sic: "20412",
  },
  {
    id: 158,
    text: "Manufacture of perfumes and toilet preparations",
    sic: "20420",
  },
  { id: 159, text: "Manufacture of explosives", sic: "20510" },
  { id: 160, text: "Manufacture of glues", sic: "20520" },
  { id: 161, text: "Manufacture of essential oils", sic: "20530" },
  {
    id: 162,
    text: "Manufacture of other chemical products n.e.c.",
    sic: "20590",
  },
  { id: 163, text: "Manufacture of man-made fibres", sic: "20600" },
  {
    id: 164,
    text: "Manufacture of basic pharmaceutical products",
    sic: "21100",
  },
  {
    id: 165,
    text: "Manufacture of pharmaceutical preparations",
    sic: "21200",
  },
  {
    id: 166,
    text: "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres",
    sic: "22110",
  },
  { id: 167, text: "Manufacture of other rubber products", sic: "22190" },
  {
    id: 168,
    text: "Manufacture of plastic plates, sheets, tubes and profiles",
    sic: "22210",
  },
  { id: 169, text: "Manufacture of plastic packing goods", sic: "22220" },
  { id: 170, text: "Manufacture of builders ware of plastic", sic: "22230" },
  { id: 171, text: "Manufacture of other plastic products", sic: "22290" },
  { id: 172, text: "Manufacture of flat glass", sic: "23110" },
  { id: 173, text: "Shaping and processing of flat glass", sic: "23120" },
  { id: 174, text: "Manufacture of hollow glass", sic: "23130" },
  { id: 175, text: "Manufacture of glass fibres", sic: "23140" },
  {
    id: 176,
    text: "Manufacture and processing of other glass, including technical glassware",
    sic: "23190",
  },
  { id: 177, text: "Manufacture of refractory products", sic: "23200" },
  { id: 178, text: "Manufacture of ceramic tiles and flags", sic: "23310" },
  {
    id: 179,
    text: "Manufacture of bricks, tiles and construction products, in baked clay",
    sic: "23320",
  },
  {
    id: 180,
    text: "Manufacture of ceramic household and ortextntal articles",
    sic: "23410",
  },
  { id: 181, text: "Manufacture of ceramic sanitary fixtures", sic: "23420" },
  {
    id: 182,
    text: "Manufacture of ceramic insulators and insulating fittings",
    sic: "23430",
  },
  {
    id: 183,
    text: "Manufacture of other technical ceramic products",
    sic: "23440",
  },
  {
    id: 184,
    text: "Manufacture of other ceramic products n.e.c.",
    sic: "23490",
  },
  { id: 185, text: "Manufacture of cement", sic: "23510" },
  { id: 186, text: "Manufacture of lime and plaster", sic: "23520" },
  {
    id: 187,
    text: "Manufacture of concrete products for construction purposes",
    sic: "23610",
  },
  {
    id: 188,
    text: "Manufacture of plaster products for construction purposes",
    sic: "23620",
  },
  { id: 189, text: "Manufacture of ready-mixed concrete", sic: "23630" },
  { id: 190, text: "Manufacture of mortars", sic: "23640" },
  { id: 191, text: "Manufacture of fibre cement", sic: "23650" },
  {
    id: 192,
    text: "Manufacture of other articles of concrete, plaster and cement",
    sic: "23690",
  },
  { id: 193, text: "Cutting, shaping and finishing of stone", sic: "23700" },
  { id: 194, text: "Production of abrasive products", sic: "23910" },
  {
    id: 195,
    text: "Manufacture of other non-metallic mineral products n.e.c.",
    sic: "23990",
  },
  {
    id: 196,
    text: "Manufacture of basic iron and steel and of ferro-alloys",
    sic: "24100",
  },
  {
    id: 197,
    text: "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
    sic: "24200",
  },
  { id: 198, text: "Cold drawing of bars", sic: "24310" },
  { id: 199, text: "Cold rolling of narrow strip", sic: "24320" },
  { id: 200, text: "Cold forming or folding", sic: "24330" },
  { id: 201, text: "Cold drawing of wire", sic: "24340" },
  { id: 202, text: "Precious metals production", sic: "24410" },
  { id: 203, text: "Aluminium production", sic: "24420" },
  { id: 204, text: "Lead, zinc and tin production", sic: "24430" },
  { id: 205, text: "Copper production", sic: "24440" },
  { id: 206, text: "Other non-ferrous metal production", sic: "24450" },
  { id: 207, text: "Processing of nuclear fuel", sic: "24460" },
  { id: 208, text: "Casting of iron", sic: "24510" },
  { id: 209, text: "Casting of steel", sic: "24520" },
  { id: 210, text: "Casting of light metals", sic: "24530" },
  { id: 211, text: "Casting of other non-ferrous metals", sic: "24540" },
  {
    id: 212,
    text: "Manufacture of metal structures and parts of structures",
    sic: "25110",
  },
  {
    id: 213,
    text: "Manufacture of doors and windows of metal",
    sic: "25120",
  },
  {
    id: 214,
    text: "Manufacture of central heating radiators and boilers",
    sic: "25210",
  },
  {
    id: 215,
    text: "Manufacture of other tanks, reservoirs and containers of metal",
    sic: "25290",
  },
  {
    id: 216,
    text: "Manufacture of steam generators, except central heating hot water boilers",
    sic: "25300",
  },
  { id: 217, text: "Manufacture of weapons and ammunition", sic: "25400" },
  {
    id: 218,
    text: "Forging, pressing, stamping and roll-forming of metal; powder metallurgy",
    sic: "25500",
  },
  { id: 219, text: "Treatment and coating of metals", sic: "25610" },
  { id: 220, text: "Machining", sic: "25620" },
  { id: 221, text: "Manufacture of cutlery", sic: "25710" },
  { id: 222, text: "Manufacture of locks and hinges", sic: "25720" },
  { id: 223, text: "Manufacture of tools", sic: "25730" },
  {
    id: 224,
    text: "Manufacture of steel drums and similar containers",
    sic: "25910",
  },
  { id: 225, text: "Manufacture of light metal packaging", sic: "25920" },
  {
    id: 226,
    text: "Manufacture of wire products, chain and springs",
    sic: "25930",
  },
  {
    id: 227,
    text: "Manufacture of fasteners and screw machine products",
    sic: "25940",
  },
  {
    id: 228,
    text: "Manufacture of other fabricated metal products n.e.c.",
    sic: "25990",
  },
  { id: 229, text: "Manufacture of electronic components", sic: "26110" },
  { id: 230, text: "Manufacture of loaded electronic boards", sic: "26120" },
  {
    id: 231,
    text: "Manufacture of computers and peripheral equipment",
    sic: "26200",
  },
  {
    id: 232,
    text: "Manufacture of telegraph and telephone apparatus and equipment",
    sic: "26301",
  },
  {
    id: 233,
    text: "Manufacture of communication equipment other than telegraph, and telephone apparatus and equipment",
    sic: "26309",
  },
  { id: 234, text: "Manufacture of consumer electronics", sic: "26400" },
  {
    id: 235,
    text: "Manufacture of electronic measuring, testing etc. equipment, not for industrial process control",
    sic: "26511",
  },
  {
    id: 236,
    text: "Manufacture of electronic industrial process control equipment",
    sic: "26512",
  },
  {
    id: 237,
    text: "Manufacture of non-electronic measuring, testing etc. equipment, not for industrial process control",
    sic: "26513",
  },
  {
    id: 238,
    text: "Manufacture of non-electronic industrial process control equipment",
    sic: "26514",
  },
  { id: 239, text: "Manufacture of watches and clocks", sic: "26520" },
  {
    id: 240,
    text: "Manufacture of irradiation, electromedical and electrotherapeutic equipment",
    sic: "26600",
  },
  {
    id: 241,
    text: "Manufacture of optical precision instruments",
    sic: "26701",
  },
  {
    id: 242,
    text: "Manufacture of photographic and cinematographic equipment",
    sic: "26702",
  },
  {
    id: 243,
    text: "Manufacture of magnetic and optical media",
    sic: "26800",
  },
  {
    id: 244,
    text: "Manufacture of electric motors, generators and transformers",
    sic: "27110",
  },
  {
    id: 245,
    text: "Manufacture of electricity distribution and control apparatus",
    sic: "27120",
  },
  {
    id: 246,
    text: "Manufacture of batteries and accumulators",
    sic: "27200",
  },
  { id: 247, text: "Manufacture of fibre optic cables", sic: "27310" },
  {
    id: 248,
    text: "Manufacture of other electronic and electric wires and cables",
    sic: "27320",
  },
  { id: 249, text: "Manufacture of wiring devices", sic: "27330" },
  {
    id: 250,
    text: "Manufacture of electric lighting equipment",
    sic: "27400",
  },
  {
    id: 251,
    text: "Manufacture of electric domestic appliances",
    sic: "27510",
  },
  {
    id: 252,
    text: "Manufacture of non-electric domestic appliances",
    sic: "27520",
  },
  {
    id: 253,
    text: "Manufacture of other electrical equipment",
    sic: "27900",
  },
  {
    id: 254,
    text: "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
    sic: "28110",
  },
  { id: 255, text: "Manufacture of fluid power equipment", sic: "28120" },
  { id: 256, text: "Manufacture of pumps", sic: "28131" },
  { id: 257, text: "Manufacture of compressors", sic: "28132" },
  { id: 258, text: "Manufacture of taps and valves", sic: "28140" },
  {
    id: 259,
    text: "Manufacture of bearings, gears, gearing and driving elements",
    sic: "28150",
  },
  {
    id: 260,
    text: "Manufacture of ovens, furnaces and furnace burners",
    sic: "28210",
  },
  {
    id: 261,
    text: "Manufacture of lifting and handling equipment",
    sic: "28220",
  },
  {
    id: 262,
    text: "Manufacture of office machinery and equipment (except computers and peripheral equipment)",
    sic: "28230",
  },
  { id: 263, text: "Manufacture of power-driven hand tools", sic: "28240" },
  {
    id: 264,
    text: "Manufacture of non-domestic cooling and ventilation equipment",
    sic: "28250",
  },
  {
    id: 265,
    text: "Manufacture of other general-purpose machinery n.e.c.",
    sic: "28290",
  },
  { id: 266, text: "Manufacture of agricultural tractors", sic: "28301" },
  {
    id: 267,
    text: "Manufacture of agricultural and forestry machinery other than tractors",
    sic: "28302",
  },
  { id: 268, text: "Manufacture of metal forming machinery", sic: "28410" },
  { id: 269, text: "Manufacture of other machine tools", sic: "28490" },
  { id: 270, text: "Manufacture of machinery for metallurgy", sic: "28910" },
  { id: 271, text: "Manufacture of machinery for mining", sic: "28921" },
  { id: 272, text: "Manufacture of earthmoving equipment", sic: "28922" },
  {
    id: 273,
    text: "Manufacture of equipment for concrete crushing and screening and roadworks",
    sic: "28923",
  },
  {
    id: 274,
    text: "Manufacture of machinery for food, beverage and tobacco processing",
    sic: "28930",
  },
  {
    id: 275,
    text: "Manufacture of machinery for textile, apparel and leather production",
    sic: "28940",
  },
  {
    id: 276,
    text: "Manufacture of machinery for paper and paperboard production",
    sic: "28950",
  },
  {
    id: 277,
    text: "Manufacture of plastics and rubber machinery",
    sic: "28960",
  },
  {
    id: 278,
    text: "Manufacture of other special-purpose machinery n.e.c.",
    sic: "28990",
  },
  { id: 279, text: "Manufacture of motor vehicles", sic: "29100" },
  {
    id: 280,
    text: "Manufacture of bodies (coachwork) for motor vehicles (except caravans)",
    sic: "29201",
  },
  {
    id: 281,
    text: "Manufacture of trailers and semi-trailers",
    sic: "29202",
  },
  { id: 282, text: "Manufacture of caravans", sic: "29203" },
  {
    id: 283,
    text: "Manufacture of electrical and electronic equipment for motor vehicles and their engines",
    sic: "29310",
  },
  {
    id: 284,
    text: "Manufacture of other parts and accessories for motor vehicles",
    sic: "29320",
  },
  {
    id: 285,
    text: "Building of ships and floating structures",
    sic: "30110",
  },
  { id: 286, text: "Building of pleasure and sporting boats", sic: "30120" },
  {
    id: 287,
    text: "Manufacture of railway locomotives and rolling stock",
    sic: "30200",
  },
  {
    id: 288,
    text: "Manufacture of air and spacecraft and related machinery",
    sic: "30300",
  },
  {
    id: 289,
    text: "Manufacture of military fighting vehicles",
    sic: "30400",
  },
  { id: 290, text: "Manufacture of motorcycles", sic: "30910" },
  {
    id: 291,
    text: "Manufacture of bicycles and invalid carriages",
    sic: "30920",
  },
  {
    id: 292,
    text: "Manufacture of other transport equipment n.e.c.",
    sic: "30990",
  },
  { id: 293, text: "Manufacture of office and shop furniture", sic: "31010" },
  { id: 294, text: "Manufacture of kitchen furniture", sic: "31020" },
  { id: 295, text: "Manufacture of mattresses", sic: "31030" },
  { id: 296, text: "Manufacture of other furniture", sic: "31090" },
  { id: 297, text: "Striking of coins", sic: "32110" },
  {
    id: 298,
    text: "Manufacture of jewellery and related articles",
    sic: "32120",
  },
  {
    id: 299,
    text: "Manufacture of imitation jewellery and related articles",
    sic: "32130",
  },
  { id: 300, text: "Manufacture of musical instruments", sic: "32200" },
  { id: 301, text: "Manufacture of sports goods", sic: "32300" },
  {
    id: 302,
    text: "Manufacture of professional and arcade games and toys",
    sic: "32401",
  },
  {
    id: 303,
    text: "Manufacture of other games and toys, n.e.c.",
    sic: "32409",
  },
  {
    id: 304,
    text: "Manufacture of medical and dental instruments and supplies",
    sic: "32500",
  },
  { id: 305, text: "Manufacture of brooms and brushes", sic: "32910" },
  { id: 306, text: "Other manufacturing n.e.c.", sic: "32990" },
  { id: 307, text: "Repair of fabricated metal products", sic: "33110" },
  { id: 308, text: "Repair of machinery", sic: "33120" },
  {
    id: 309,
    text: "Repair of electronic and optical equipment",
    sic: "33130",
  },
  { id: 310, text: "Repair of electrical equipment", sic: "33140" },
  {
    id: 311,
    text: "Repair and maintenance of ships and boats",
    sic: "33150",
  },
  {
    id: 312,
    text: "Repair and maintenance of aircraft and spacecraft",
    sic: "33160",
  },
  {
    id: 313,
    text: "Repair and maintenance of other transport equipment n.e.c.",
    sic: "33170",
  },
  { id: 314, text: "Repair of other equipment", sic: "33190" },
  {
    id: 315,
    text: "Installation of industrial machinery and equipment",
    sic: "33200",
  },
  { id: 316, text: "Production of electricity", sic: "35110" },
  { id: 317, text: "Transmission of electricity", sic: "35120" },
  { id: 318, text: "Distribution of electricity", sic: "35130" },
  { id: 319, text: "Trade of electricity", sic: "35140" },
  { id: 320, text: "Manufacture of gas", sic: "35210" },
  {
    id: 321,
    text: "Distribution of gaseous fuels through mains",
    sic: "35220",
  },
  { id: 322, text: "Trade of gas through mains", sic: "35230" },
  { id: 323, text: "Steam and air conditioning supply", sic: "35300" },
  { id: 324, text: "Water collection, treatment and supply", sic: "36000" },
  { id: 325, text: "Sewerage", sic: "37000" },
  { id: 326, text: "Collection of non-hazardous waste", sic: "38110" },
  { id: 327, text: "Collection of hazardous waste", sic: "38120" },
  {
    id: 328,
    text: "Treatment and disposal of non-hazardous waste",
    sic: "38210",
  },
  {
    id: 329,
    text: "Treatment and disposal of hazardous waste",
    sic: "38220",
  },
  { id: 330, text: "Dismantling of wrecks", sic: "38310" },
  { id: 331, text: "Recovery of sorted materials", sic: "38320" },
  {
    id: 332,
    text: "Remediation activities and other waste management services",
    sic: "39000",
  },
  { id: 333, text: "Development of building projects", sic: "41100" },
  { id: 334, text: "Construction of commercial buildings", sic: "41201" },
  { id: 335, text: "Construction of domestic buildings", sic: "41202" },
  { id: 336, text: "Construction of roads and motorways", sic: "42110" },
  {
    id: 337,
    text: "Construction of railways and underground railways",
    sic: "42120",
  },
  { id: 338, text: "Construction of bridges and tunnels", sic: "42130" },
  {
    id: 339,
    text: "Construction of utility projects for fluids",
    sic: "42210",
  },
  {
    id: 340,
    text: "Construction of utility projects for electricity and telecommunications",
    sic: "42220",
  },
  { id: 341, text: "Construction of water projects", sic: "42910" },
  {
    id: 342,
    text: "Construction of other civil engineering projects n.e.c.",
    sic: "42990",
  },
  { id: 343, text: "Demolition", sic: "43110" },
  { id: 344, text: "Site preparation", sic: "43120" },
  { id: 345, text: "Test drilling and boring", sic: "43130" },
  { id: 346, text: "Electrical installation", sic: "43210" },
  {
    id: 347,
    text: "Plumbing, heat and air-conditioning installation",
    sic: "43220",
  },
  { id: 348, text: "Other construction installation", sic: "43290" },
  { id: 349, text: "Plastering", sic: "43310" },
  { id: 350, text: "Joinery installation", sic: "43320" },
  { id: 351, text: "Floor and wall covering", sic: "43330" },
  { id: 352, text: "Painting", sic: "43341" },
  { id: 353, text: "Glazing", sic: "43342" },
  { id: 354, text: "Other building completion and finishing", sic: "43390" },
  { id: 355, text: "Roofing activities", sic: "43910" },
  { id: 356, text: "Scaffold erection", sic: "43991" },
  {
    id: 357,
    text: "Other specialised construction activities n.e.c.",
    sic: "43999",
  },
  {
    id: 358,
    text: "Sale of new cars and light motor vehicles",
    sic: "45111",
  },
  {
    id: 359,
    text: "Sale of used cars and light motor vehicles",
    sic: "45112",
  },
  { id: 360, text: "Sale of other motor vehicles", sic: "45190" },
  { id: 361, text: "Maintenance and repair of motor vehicles", sic: "45200" },
  {
    id: 362,
    text: "Wholesale trade of motor vehicle parts and accessories",
    sic: "45310",
  },
  {
    id: 363,
    text: "Retail trade of motor vehicle parts and accessories",
    sic: "45320",
  },
  {
    id: 364,
    text: "Sale, maintenance and repair of motorcycles and related parts and accessories",
    sic: "45400",
  },
  {
    id: 365,
    text: "Agents selling agricultural raw materials, livestock, textile raw materials and semi-finished goods",
    sic: "46110",
  },
  {
    id: 366,
    text: "Agents involved in the sale of fuels, ores, metals and industrial chemicals",
    sic: "46120",
  },
  {
    id: 367,
    text: "Agents involved in the sale of timber and building materials",
    sic: "46130",
  },
  {
    id: 368,
    text: "Agents involved in the sale of machinery, industrial equipment, ships and aircraft",
    sic: "46140",
  },
  {
    id: 369,
    text: "Agents involved in the sale of furniture, household goods, hardware and ironmongery",
    sic: "46150",
  },
  {
    id: 370,
    text: "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods",
    sic: "46160",
  },
  {
    id: 371,
    text: "Agents involved in the sale of food, beverages and tobacco",
    sic: "46170",
  },
  {
    id: 372,
    text: "Agents specialised in the sale of other particular products",
    sic: "46180",
  },
  {
    id: 373,
    text: "Agents involved in the sale of a variety of goods",
    sic: "46190",
  },
  {
    id: 374,
    text: "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",
    sic: "46210",
  },
  { id: 375, text: "Wholesale of flowers and plants", sic: "46220" },
  { id: 376, text: "Wholesale of live animals", sic: "46230" },
  { id: 377, text: "Wholesale of hides, skins and leather", sic: "46240" },
  { id: 378, text: "Wholesale of fruit and vegetables", sic: "46310" },
  { id: 379, text: "Wholesale of meat and meat products", sic: "46320" },
  {
    id: 380,
    text: "Wholesale of dairy products, eggs and edible oils and fats",
    sic: "46330",
  },
  {
    id: 381,
    text: "Wholesale of fruit and vegetable juices, mineral water and soft drinks",
    sic: "46341",
  },
  {
    id: 382,
    text: "Wholesale of wine, beer, spirits and other alcoholic beverages",
    sic: "46342",
  },
  { id: 383, text: "Wholesale of tobacco products", sic: "46350" },
  {
    id: 384,
    text: "Wholesale of sugar and chocolate and sugar confectionery",
    sic: "46360",
  },
  {
    id: 385,
    text: "Wholesale of coffee, tea, cocoa and spices",
    sic: "46370",
  },
  {
    id: 386,
    text: "Wholesale of other food, including fish, crustaceans and molluscs",
    sic: "46380",
  },
  {
    id: 387,
    text: "Non-specialised wholesale of food, beverages and tobacco",
    sic: "46390",
  },
  { id: 388, text: "Wholesale of textiles", sic: "46410" },
  { id: 389, text: "Wholesale of clothing and footwear", sic: "46420" },
  {
    id: 390,
    text: "Wholesale of audio tapes, records, CDs and video tapes and the equipment on which these are played",
    sic: "46431",
  },
  {
    id: 391,
    text: "Wholesale of radio, television goods \u0026 electrical household appliances (other than records, tapes, CD\u0027s \u0026 video tapes and the equipment used for playing them)",
    sic: "46439",
  },
  {
    id: 392,
    text: "Wholesale of china and glassware and cleaning materials",
    sic: "46440",
  },
  { id: 393, text: "Wholesale of perfume and cosmetics", sic: "46450" },
  { id: 394, text: "Wholesale of pharmaceutical goods", sic: "46460" },
  {
    id: 395,
    text: "Wholesale of furniture, carpets and lighting equipment",
    sic: "46470",
  },
  { id: 396, text: "Wholesale of watches and jewellery", sic: "46480" },
  { id: 397, text: "Wholesale of musical instruments", sic: "46491" },
  {
    id: 398,
    text: "Wholesale of household goods (other than musical instruments) n.e.c",
    sic: "46499",
  },
  {
    id: 399,
    text: "Wholesale of computers, computer peripheral equipment and software",
    sic: "46510",
  },
  {
    id: 400,
    text: "Wholesale of electronic and telecommunications equipment and parts",
    sic: "46520",
  },
  {
    id: 401,
    text: "Wholesale of agricultural machinery, equipment and supplies",
    sic: "46610",
  },
  { id: 402, text: "Wholesale of machine tools", sic: "46620" },
  {
    id: 403,
    text: "Wholesale of mining, construction and civil engineering machinery",
    sic: "46630",
  },
  {
    id: 404,
    text: "Wholesale of machinery for the textile industry and of sewing and knitting machines",
    sic: "46640",
  },
  { id: 405, text: "Wholesale of office furniture", sic: "46650" },
  {
    id: 406,
    text: "Wholesale of other office machinery and equipment",
    sic: "46660",
  },
  {
    id: 407,
    text: "Wholesale of other machinery and equipment",
    sic: "46690",
  },
  {
    id: 408,
    text: "Wholesale of petroleum and petroleum products",
    sic: "46711",
  },
  {
    id: 409,
    text: "Wholesale of other fuels and related products",
    sic: "46719",
  },
  { id: 410, text: "Wholesale of metals and metal ores", sic: "46720" },
  {
    id: 411,
    text: "Wholesale of wood, construction materials and sanitary equipment",
    sic: "46730",
  },
  {
    id: 412,
    text: "Wholesale of hardware, plumbing and heating equipment and supplies",
    sic: "46740",
  },
  { id: 413, text: "Wholesale of chemical products", sic: "46750" },
  { id: 414, text: "Wholesale of other intermediate products", sic: "46760" },
  { id: 415, text: "Wholesale of waste and scrap", sic: "46770" },
  { id: 416, text: "Non-specialised wholesale trade", sic: "46900" },
  {
    id: 417,
    text: "Retail sale in non-specialised stores with food, beverages or tobacco predominating",
    sic: "47110",
  },
  {
    id: 418,
    text: "Other retail sale in non-specialised stores",
    sic: "47190",
  },
  {
    id: 419,
    text: "Retail sale of fruit and vegetables in specialised stores",
    sic: "47210",
  },
  {
    id: 420,
    text: "Retail sale of meat and meat products in specialised stores",
    sic: "47220",
  },
  {
    id: 421,
    text: "Retail sale of fish, crustaceans and molluscs in specialised stores",
    sic: "47230",
  },
  {
    id: 422,
    text: "Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores",
    sic: "47240",
  },
  {
    id: 423,
    text: "Retail sale of beverages in specialised stores",
    sic: "47250",
  },
  {
    id: 424,
    text: "Retail sale of tobacco products in specialised stores",
    sic: "47260",
  },
  {
    id: 425,
    text: "Other retail sale of food in specialised stores",
    sic: "47290",
  },
  {
    id: 426,
    text: "Retail sale of automotive fuel in specialised stores",
    sic: "47300",
  },
  {
    id: 427,
    text: "Retail sale of computers, peripheral units and software in specialised stores",
    sic: "47410",
  },
  { id: 428, text: "Retail sale of mobile telephones", sic: "47421" },
  {
    id: 429,
    text: "Retail sale of telecommunications equipment other than mobile telephones",
    sic: "47429",
  },
  {
    id: 430,
    text: "Retail sale of audio and video equipment in specialised stores",
    sic: "47430",
  },
  {
    id: 431,
    text: "Retail sale of textiles in specialised stores",
    sic: "47510",
  },
  {
    id: 432,
    text: "Retail sale of hardware, paints and glass in specialised stores",
    sic: "47520",
  },
  {
    id: 433,
    text: "Retail sale of carpets, rugs, wall and floor coverings in specialised stores",
    sic: "47530",
  },
  {
    id: 434,
    text: "Retail sale of electrical household appliances in specialised stores",
    sic: "47540",
  },
  {
    id: 435,
    text: "Retail sale of musical instruments and scores",
    sic: "47591",
  },
  {
    id: 436,
    text: "Retail of furniture, lighting, and similar (not musical instruments or scores) in specialised store",
    sic: "47599",
  },
  {
    id: 437,
    text: "Retail sale of books in specialised stores",
    sic: "47610",
  },
  {
    id: 438,
    text: "Retail sale of newspapers and stationery in specialised stores",
    sic: "47620",
  },
  {
    id: 439,
    text: "Retail sale of music and video recordings in specialised stores",
    sic: "47630",
  },
  {
    id: 440,
    text: "Retail sale of sports goods, fishing gear, camping goods, boats and bicycles",
    sic: "47640",
  },
  {
    id: 441,
    text: "Retail sale of games and toys in specialised stores",
    sic: "47650",
  },
  {
    id: 442,
    text: "Retail sale of clothing in specialised stores",
    sic: "47710",
  },
  {
    id: 443,
    text: "Retail sale of footwear in specialised stores",
    sic: "47721",
  },
  {
    id: 444,
    text: "Retail sale of leather goods in specialised stores",
    sic: "47722",
  },
  { id: 445, text: "Dispensing chemist in specialised stores", sic: "47730" },
  { id: 446, text: "Retail sale of hearing aids", sic: "47741" },
  {
    id: 447,
    text: "Retail sale of medical and orthopaedic goods in specialised stores (not incl. hearing aids) n.e.c.",
    sic: "47749",
  },
  {
    id: 448,
    text: "Retail sale of cosmetic and toilet articles in specialised stores",
    sic: "47750",
  },
  {
    id: 449,
    text: "Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food in specialised stores",
    sic: "47760",
  },
  {
    id: 450,
    text: "Retail sale of watches and jewellery in specialised stores",
    sic: "47770",
  },
  { id: 451, text: "Retail sale in commercial art galleries", sic: "47781" },
  { id: 452, text: "Retail sale by opticians", sic: "47782" },
  {
    id: 453,
    text: "Other retail sale of new goods in specialised stores (not commercial art galleries and opticians)",
    sic: "47789",
  },
  {
    id: 454,
    text: "Retail sale of antiques including antique books in stores",
    sic: "47791",
  },
  {
    id: 455,
    text: "Retail sale of other second-hand goods in stores (not incl. antiques)",
    sic: "47799",
  },
  {
    id: 456,
    text: "Retail sale via stalls and markets of food, beverages and tobacco products",
    sic: "47810",
  },
  {
    id: 457,
    text: "Retail sale via stalls and markets of textiles, clothing and footwear",
    sic: "47820",
  },
  {
    id: 458,
    text: "Retail sale via stalls and markets of other goods",
    sic: "47890",
  },
  {
    id: 459,
    text: "Retail sale via mail order houses or via Internet",
    sic: "47910",
  },
  {
    id: 460,
    text: "Other retail sale not in stores, stalls or markets",
    sic: "47990",
  },
  { id: 461, text: "Passenger rail transport, interurban", sic: "49100" },
  { id: 462, text: "Freight rail transport", sic: "49200" },
  {
    id: 463,
    text: "Urban and suburban passenger railway transportation by underground, metro and similar systems",
    sic: "49311",
  },
  {
    id: 464,
    text: "Other urban, suburban or metropolitan passenger land transport (not underground, metro or similar)",
    sic: "49319",
  },
  { id: 465, text: "Taxi operation", sic: "49320" },
  { id: 466, text: "Other passenger land transport", sic: "49390" },
  { id: 467, text: "Freight transport by road", sic: "49410" },
  { id: 468, text: "Removal services", sic: "49420" },
  { id: 469, text: "Transport via pipeline", sic: "49500" },
  {
    id: 470,
    text: "Sea and coastal passenger water transport",
    sic: "50100",
  },
  { id: 471, text: "Sea and coastal freight water transport", sic: "50200" },
  { id: 472, text: "Inland passenger water transport", sic: "50300" },
  { id: 473, text: "Inland freight water transport", sic: "50400" },
  { id: 474, text: "Scheduled passenger air transport", sic: "51101" },
  { id: 475, text: "Non-scheduled passenger air transport", sic: "51102" },
  { id: 476, text: "Freight air transport", sic: "51210" },
  { id: 477, text: "Space transport", sic: "51220" },
  {
    id: 478,
    text: "Operation of warehousing and storage facilities for water transport activities",
    sic: "52101",
  },
  {
    id: 479,
    text: "Operation of warehousing and storage facilities for air transport activities",
    sic: "52102",
  },
  {
    id: 480,
    text: "Operation of warehousing and storage facilities for land transport activities",
    sic: "52103",
  },
  { id: 481, text: "Operation of rail freight terminals", sic: "52211" },
  {
    id: 482,
    text: "Operation of rail passenger facilities at railway stations",
    sic: "52212",
  },
  {
    id: 483,
    text: "Operation of bus and coach passenger facilities at bus and coach stations",
    sic: "52213",
  },
  {
    id: 484,
    text: "Other service activities incidental to land transportation, n.e.c.",
    sic: "52219",
  },
  {
    id: 485,
    text: "Service activities incidental to water transportation",
    sic: "52220",
  },
  {
    id: 486,
    text: "Service activities incidental to air transportation",
    sic: "52230",
  },
  {
    id: 487,
    text: "Cargo handling for water transport activities",
    sic: "52241",
  },
  {
    id: 488,
    text: "Cargo handling for air transport activities",
    sic: "52242",
  },
  {
    id: 489,
    text: "Cargo handling for land transport activities",
    sic: "52243",
  },
  { id: 490, text: "Other transportation support activities", sic: "52290" },
  {
    id: 491,
    text: "Postal activities under universal service obligation",
    sic: "53100",
  },
  { id: 492, text: "Licensed carriers", sic: "53201" },
  { id: 493, text: "Unlicensed carriers", sic: "53202" },
  { id: 494, text: "Hotels and similar accommodation", sic: "55100" },
  { id: 495, text: "Holiday centres and villages", sic: "55201" },
  { id: 496, text: "Youth hostels", sic: "55202" },
  {
    id: 497,
    text: "Other holiday and other collective accommodation",
    sic: "55209",
  },
  {
    id: 498,
    text: "Recreational vehicle parks, trailer parks and camping grounds",
    sic: "55300",
  },
  { id: 499, text: "Other accommodation", sic: "55900" },
  { id: 500, text: "Licenced restaurants", sic: "56101" },
  { id: 501, text: "Unlicenced restaurants and cafes", sic: "56102" },
  {
    id: 502,
    text: "Take-away food shops and mobile food stands",
    sic: "56103",
  },
  { id: 503, text: "Event catering activities", sic: "56210" },
  { id: 504, text: "Other food services", sic: "56290" },
  { id: 505, text: "Licenced clubs", sic: "56301" },
  { id: 506, text: "Public houses and bars", sic: "56302" },
  { id: 507, text: "Book publishing", sic: "58110" },
  {
    id: 508,
    text: "Publishing of directories and mailing lists",
    sic: "58120",
  },
  { id: 509, text: "Publishing of newspapers", sic: "58130" },
  { id: 510, text: "Publishing of learned journals", sic: "58141" },
  {
    id: 511,
    text: "Publishing of consumer and business journals and periodicals",
    sic: "58142",
  },
  { id: 512, text: "Other publishing activities", sic: "58190" },
  { id: 513, text: "Publishing of computer games", sic: "58210" },
  { id: 514, text: "Other software publishing", sic: "58290" },
  { id: 515, text: "Motion picture production activities", sic: "59111" },
  { id: 516, text: "Video production activities", sic: "59112" },
  {
    id: 517,
    text: "Television programme production activities",
    sic: "59113",
  },
  {
    id: 518,
    text: "Motion picture, video and television programme post-production activities",
    sic: "59120",
  },
  { id: 519, text: "Motion picture distribution activities", sic: "59131" },
  { id: 520, text: "Video distribution activities", sic: "59132" },
  {
    id: 521,
    text: "Television programme distribution activities",
    sic: "59133",
  },
  { id: 522, text: "Motion picture projection activities", sic: "59140" },
  {
    id: 523,
    text: "Sound recording and music publishing activities",
    sic: "59200",
  },
  { id: 524, text: "Radio broadcasting", sic: "60100" },
  {
    id: 525,
    text: "Television programming and broadcasting activities",
    sic: "60200",
  },
  { id: 526, text: "Wired telecommunications activities", sic: "61100" },
  { id: 527, text: "Wireless telecommunications activities", sic: "61200" },
  { id: 528, text: "Satellite telecommunications activities", sic: "61300" },
  { id: 529, text: "Other telecommunications activities", sic: "61900" },
  {
    id: 530,
    text: "Ready-made interactive leisure and entertainment software development",
    sic: "62011",
  },
  {
    id: 531,
    text: "Business and domestic software development",
    sic: "62012",
  },
  {
    id: 532,
    text: "Information technology consultancy activities",
    sic: "62020",
  },
  {
    id: 533,
    text: "Computer facilities management activities",
    sic: "62030",
  },
  {
    id: 534,
    text: "Other information technology service activities",
    sic: "62090",
  },
  {
    id: 535,
    text: "Data processing, hosting and related activities",
    sic: "63110",
  },
  { id: 536, text: "Web portals", sic: "63120" },
  { id: 537, text: "News agency activities", sic: "63910" },
  {
    id: 538,
    text: "Other information service activities n.e.c.",
    sic: "63990",
  },
  { id: 539, text: "Central banking", sic: "64110" },
  { id: 540, text: "Banks", sic: "64191" },
  { id: 541, text: "Building societies", sic: "64192" },
  {
    id: 542,
    text: "Activities of agricultural holding companies",
    sic: "64201",
  },
  {
    id: 543,
    text: "Activities of production holding companies",
    sic: "64202",
  },
  {
    id: 544,
    text: "Activities of construction holding companies",
    sic: "64203",
  },
  {
    id: 545,
    text: "Activities of distribution holding companies",
    sic: "64204",
  },
  {
    id: 546,
    text: "Activities of financial services holding companies",
    sic: "64205",
  },
  {
    id: 547,
    text: "Activities of other holding companies n.e.c.",
    sic: "64209",
  },
  { id: 548, text: "Activities of investment trusts", sic: "64301" },
  { id: 549, text: "Activities of unit trusts", sic: "64302" },
  {
    id: 550,
    text: "Activities of venture and development capital companies",
    sic: "64303",
  },
  {
    id: 551,
    text: "Activities of open-ended investment companies",
    sic: "64304",
  },
  { id: 552, text: "Activities of property unit trusts", sic: "64305" },
  {
    id: 553,
    text: "Activities of real estate investment trusts",
    sic: "64306",
  },
  { id: 554, text: "Financial leasing", sic: "64910" },
  {
    id: 555,
    text: "Credit granting by non-deposit taking finance houses and other specialist consumer credit grantors",
    sic: "64921",
  },
  { id: 556, text: "Activities of mortgage finance companies", sic: "64922" },
  { id: 557, text: "Other credit granting n.e.c.", sic: "64929" },
  { id: 558, text: "Security dealing on own account", sic: "64991" },
  { id: 559, text: "Factoring", sic: "64992" },
  {
    id: 560,
    text: "Financial intermediation not elsewhere classified",
    sic: "64999",
  },
  { id: 561, text: "Life insurance", sic: "65110" },
  { id: 562, text: "Non-life insurance", sic: "65120" },
  { id: 563, text: "Life reinsurance", sic: "65201" },
  { id: 564, text: "Non-life reinsurance", sic: "65202" },
  { id: 565, text: "Pension funding", sic: "65300" },
  { id: 566, text: "Administration of financial markets", sic: "66110" },
  {
    id: 567,
    text: "Security and commodity contracts dealing activities",
    sic: "66120",
  },
  {
    id: 568,
    text: "Activities auxiliary to financial intermediation n.e.c.",
    sic: "66190",
  },
  { id: 569, text: "Risk and damage evaluation", sic: "66210" },
  {
    id: 570,
    text: "Activities of insurance agents and brokers",
    sic: "66220",
  },
  {
    id: 571,
    text: "Other activities auxiliary to insurance and pension funding",
    sic: "66290",
  },
  { id: 572, text: "Fund management activities", sic: "66300" },
  { id: 573, text: "Buying and selling of own real estate", sic: "68100" },
  {
    id: 574,
    text: "Renting and operating of Housing Association real estate",
    sic: "68201",
  },
  {
    id: 575,
    text: "Letting and operating of conference and exhibition centres",
    sic: "68202",
  },
  {
    id: 576,
    text: "Other letting and operating of own or leased real estate",
    sic: "68209",
  },
  { id: 577, text: "Real estate agencies", sic: "68310" },
  {
    id: 578,
    text: "Management of real estate on a fee or contract basis",
    sic: "68320",
  },
  { id: 579, text: "Barristers at law", sic: "69101" },
  { id: 580, text: "Solicitors", sic: "69102" },
  {
    id: 581,
    text: "Activities of patent and copyright agents; other legal activities n.e.c.",
    sic: "69109",
  },
  { id: 582, text: "Accounting and auditing activities", sic: "69201" },
  { id: 583, text: "Bookkeeping activities", sic: "69202" },
  { id: 584, text: "Tax consultancy", sic: "69203" },
  { id: 585, text: "Activities of head offices", sic: "70100" },
  {
    id: 586,
    text: "Public relations and communications activities",
    sic: "70210",
  },
  { id: 587, text: "Financial management", sic: "70221" },
  {
    id: 588,
    text: "Management consultancy activities other than financial management",
    sic: "70229",
  },
  { id: 589, text: "Architectural activities", sic: "71111" },
  {
    id: 590,
    text: "Urban planning and landscape architectural activities",
    sic: "71112",
  },
  {
    id: 591,
    text: "Engineering design activities for industrial process and production",
    sic: "71121",
  },
  {
    id: 592,
    text: "Engineering related scientific and technical consulting activities",
    sic: "71122",
  },
  { id: 593, text: "Other engineering activities", sic: "71129" },
  { id: 594, text: "Technical testing and analysis", sic: "71200" },
  {
    id: 595,
    text: "Research and experimental development on biotechnology",
    sic: "72110",
  },
  {
    id: 596,
    text: "Other research and experimental development on natural sciences and engineering",
    sic: "72190",
  },
  {
    id: 597,
    text: "Research and experimental development on social sciences and humanities",
    sic: "72200",
  },
  { id: 598, text: "Advertising agencies", sic: "73110" },
  { id: 599, text: "Media representation services", sic: "73120" },
  {
    id: 600,
    text: "Market research and public opinion polling",
    sic: "73200",
  },
  { id: 601, text: "specialised design activities", sic: "74100" },
  { id: 602, text: "Portrait photographic activities", sic: "74201" },
  { id: 603, text: "Other specialist photography", sic: "74202" },
  { id: 604, text: "Film processing", sic: "74203" },
  {
    id: 605,
    text: "Photographic activities not elsewhere classified",
    sic: "74209",
  },
  {
    id: 606,
    text: "Translation and interpretation activities",
    sic: "74300",
  },
  { id: 607, text: "Environmental consulting activities", sic: "74901" },
  { id: 608, text: "Quantity surveying activities", sic: "74902" },
  {
    id: 609,
    text: "Other professional, scientific and technical activities n.e.c.",
    sic: "74909",
  },
  { id: 610, text: "Non-trading company", sic: "74990" },
  { id: 611, text: "Veterinary activities", sic: "75000" },
  {
    id: 612,
    text: "Renting and leasing of cars and light motor vehicles",
    sic: "77110",
  },
  {
    id: 613,
    text: "Renting and leasing of trucks and other heavy vehicles",
    sic: "77120",
  },
  {
    id: 614,
    text: "Renting and leasing of recreational and sports goods",
    sic: "77210",
  },
  { id: 615, text: "Renting of video tapes and disks", sic: "77220" },
  {
    id: 616,
    text: "Renting and leasing of media entertainment equipment",
    sic: "77291",
  },
  {
    id: 617,
    text: "Renting and leasing of other personal and household goods",
    sic: "77299",
  },
  {
    id: 618,
    text: "Renting and leasing of agricultural machinery and equipment",
    sic: "77310",
  },
  {
    id: 619,
    text: "Renting and leasing of construction and civil engineering machinery and equipment",
    sic: "77320",
  },
  {
    id: 620,
    text: "Renting and leasing of office machinery and equipment (including computers)",
    sic: "77330",
  },
  {
    id: 621,
    text: "Renting and leasing of passenger water transport equipment",
    sic: "77341",
  },
  {
    id: 622,
    text: "Renting and leasing of freight water transport equipment",
    sic: "77342",
  },
  {
    id: 623,
    text: "Renting and leasing of air passenger transport equipment",
    sic: "77351",
  },
  {
    id: 624,
    text: "Renting and leasing of freight air transport equipment",
    sic: "77352",
  },
  {
    id: 625,
    text: "Renting and leasing of other machinery, equipment and tangible goods n.e.c.",
    sic: "77390",
  },
  {
    id: 626,
    text: "Leasing of intellectual property and similar products, except copyright works",
    sic: "77400",
  },
  {
    id: 627,
    text: "Motion picture, television and other theatrical casting activities",
    sic: "78101",
  },
  {
    id: 628,
    text: "Other activities of employment placement agencies",
    sic: "78109",
  },
  { id: 629, text: "Temporary employment agency activities", sic: "78200" },
  {
    id: 630,
    text: "Human resources provision and management of human resources functions",
    sic: "78300",
  },
  { id: 631, text: "Travel agency activities", sic: "79110" },
  { id: 632, text: "Tour operator activities", sic: "79120" },
  { id: 633, text: "Activities of tourist guides", sic: "79901" },
  {
    id: 634,
    text: "Other reservation service activities n.e.c.",
    sic: "79909",
  },
  { id: 635, text: "Private security activities", sic: "80100" },
  { id: 636, text: "Security systems service activities", sic: "80200" },
  { id: 637, text: "Investigation activities", sic: "80300" },
  { id: 638, text: "Combined facilities support activities", sic: "81100" },
  { id: 639, text: "General cleaning of buildings", sic: "81210" },
  { id: 640, text: "Window cleaning services", sic: "81221" },
  { id: 641, text: "Specialised cleaning services", sic: "81222" },
  { id: 642, text: "Furnace and chimney cleaning services", sic: "81223" },
  {
    id: 643,
    text: "Other building and industrial cleaning activities",
    sic: "81229",
  },
  { id: 644, text: "Disinfecting and exterminating services", sic: "81291" },
  { id: 645, text: "Other cleaning services", sic: "81299" },
  { id: 646, text: "Landscape service activities", sic: "81300" },
  {
    id: 647,
    text: "Combined office administrative service activities",
    sic: "82110",
  },
  {
    id: 648,
    text: "Photocopying, document preparation and other specialised office support activities",
    sic: "82190",
  },
  { id: 649, text: "Activities of call centres", sic: "82200" },
  {
    id: 650,
    text: "Activities of exhibition and fair organisers",
    sic: "82301",
  },
  { id: 651, text: "Activities of conference organisers", sic: "82302" },
  { id: 652, text: "Activities of collection agencies", sic: "82911" },
  { id: 653, text: "Activities of credit bureaus", sic: "82912" },
  { id: 654, text: "Packaging activities", sic: "82920" },
  {
    id: 655,
    text: "Other business support service activities n.e.c.",
    sic: "82990",
  },
  { id: 656, text: "General public administration activities", sic: "84110" },
  {
    id: 657,
    text: "Regulation of health care, education, cultural and other social services, not incl. social security",
    sic: "84120",
  },
  {
    id: 658,
    text: "Regulation of and contribution to more efficient operation of businesses",
    sic: "84130",
  },
  { id: 659, text: "Foreign affairs", sic: "84210" },
  { id: 660, text: "Defence activities", sic: "84220" },
  { id: 661, text: "Justice and judicial activities", sic: "84230" },
  { id: 662, text: "Public order and safety activities", sic: "84240" },
  { id: 663, text: "Fire service activities", sic: "84250" },
  { id: 664, text: "Compulsory social security activities", sic: "84300" },
  { id: 665, text: "Pre-primary education", sic: "85100" },
  { id: 666, text: "Primary education", sic: "85200" },
  { id: 667, text: "General secondary education", sic: "85310" },
  {
    id: 668,
    text: "Technical and vocational secondary education",
    sic: "85320",
  },
  { id: 669, text: "Post-secondary non-tertiary education", sic: "85410" },
  { id: 670, text: "First-degree level higher education", sic: "85421" },
  { id: 671, text: "Post-graduate level higher education", sic: "85422" },
  { id: 672, text: "Sports and recreation education", sic: "85510" },
  { id: 673, text: "Cultural education", sic: "85520" },
  { id: 674, text: "Driving school activities", sic: "85530" },
  { id: 675, text: "Other education n.e.c.", sic: "85590" },
  { id: 676, text: "Educational support services", sic: "85600" },
  { id: 677, text: "Hospital activities", sic: "86101" },
  { id: 678, text: "Medical nursing home activities", sic: "86102" },
  { id: 679, text: "General medical practice activities", sic: "86210" },
  { id: 680, text: "Specialists medical practice activities", sic: "86220" },
  { id: 681, text: "Dental practice activities", sic: "86230" },
  { id: 682, text: "Other human health activities", sic: "86900" },
  { id: 683, text: "Residential nursing care facilities", sic: "87100" },
  {
    id: 684,
    text: "Residential care activities for learning difficulties, mental health and substance abuse",
    sic: "87200",
  },
  {
    id: 685,
    text: "Residential care activities for the elderly and disabled",
    sic: "87300",
  },
  { id: 686, text: "Other residential care activities n.e.c.", sic: "87900" },
  {
    id: 687,
    text: "Social work activities without accommodation for the elderly and disabled",
    sic: "88100",
  },
  { id: 688, text: "Child day-care activities", sic: "88910" },
  {
    id: 689,
    text: "Other social work activities without accommodation n.e.c.",
    sic: "88990",
  },
  { id: 690, text: "Performing arts", sic: "90010" },
  { id: 691, text: "Support activities to performing arts", sic: "90020" },
  { id: 692, text: "Artistic creation", sic: "90030" },
  { id: 693, text: "Operation of arts facilities", sic: "90040" },
  { id: 694, text: "Library activities", sic: "91011" },
  { id: 695, text: "Archives activities", sic: "91012" },
  { id: 696, text: "Museums activities", sic: "91020" },
  {
    id: 697,
    text: "Operation of historical sites and buildings and similar visitor attractions",
    sic: "91030",
  },
  {
    id: 698,
    text: "Botanical and zoological gardens and nature reserves activities",
    sic: "91040",
  },
  { id: 699, text: "Gambling and betting activities", sic: "92000" },
  { id: 700, text: "Operation of sports facilities", sic: "93110" },
  { id: 701, text: "Activities of sport clubs", sic: "93120" },
  { id: 702, text: "Fitness facilities", sic: "93130" },
  { id: 703, text: "Activities of racehorse owners", sic: "93191" },
  { id: 704, text: "Other sports activities", sic: "93199" },
  {
    id: 705,
    text: "Activities of amusement parks and theme parks",
    sic: "93210",
  },
  {
    id: 706,
    text: "Other amusement and recreation activities n.e.c.",
    sic: "93290",
  },
  {
    id: 707,
    text: "Activities of business and employers membership organisations",
    sic: "94110",
  },
  {
    id: 708,
    text: "Activities of professional membership organisations",
    sic: "94120",
  },
  { id: 709, text: "Activities of trade unions", sic: "94200" },
  { id: 710, text: "Activities of religious organisations", sic: "94910" },
  { id: 711, text: "Activities of political organisations", sic: "94920" },
  {
    id: 712,
    text: "Activities of other membership organisations n.e.c.",
    sic: "94990",
  },
  {
    id: 713,
    text: "Repair of computers and peripheral equipment",
    sic: "95110",
  },
  { id: 714, text: "Repair of communication equipment", sic: "95120" },
  { id: 715, text: "Repair of consumer electronics", sic: "95210" },
  {
    id: 716,
    text: "Repair of household appliances and home and garden equipment",
    sic: "95220",
  },
  { id: 717, text: "Repair of footwear and leather goods", sic: "95230" },
  { id: 718, text: "Repair of furniture and home furnishings", sic: "95240" },
  { id: 719, text: "Repair of watches, clocks and jewellery", sic: "95250" },
  {
    id: 720,
    text: "Repair of personal and household goods n.e.c.",
    sic: "95290",
  },
  {
    id: 721,
    text: "Washing and (dry-)cleaning of textile and fur products",
    sic: "96010",
  },
  { id: 722, text: "Hairdressing and other beauty treatment", sic: "96020" },
  { id: 723, text: "Funeral and related activities", sic: "96030" },
  { id: 724, text: "Physical well-being activities", sic: "96040" },
  { id: 725, text: "Other service activities n.e.c.", sic: "96090" },
  {
    id: 726,
    text: "Activities of households as employers of domestic personnel",
    sic: "97000",
  },
  { id: 727, text: "Residents property management", sic: "98000" },
  {
    id: 728,
    text: "Undifferentiated goods-producing activities of private households for own use",
    sic: "98100",
  },
  {
    id: 729,
    text: "Undifferentiated service-producing activities of private households for own use",
    sic: "98200",
  },
];

export const activities = data.map((act) => act.text);
